/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufsj.sms.GUI;

import br.edu.ufsj.sms.control.AlarmClock;
import br.edu.ufsj.sms.net.Message;
import br.edu.ufsj.sms.net.Socket;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author flavio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private Socket socket;
    private AlarmClock alarmClock;
    private Timer timer;
    public final static String INET_ADDR = "224.0.0.3";
    public final static int TIME = 1000;

    private String name;
    private int port;

    public Main(String name, int port) throws UnknownHostException {
        initComponents();
        this.name = name;
        this.port = port;
        this.socket = new Socket(this);
        this.socket.start();
        this.timer = new Timer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        shareButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Share My Sheet");

        jToolBar1.setRollover(true);

        shareButton.setText("Share My Sheet!");
        shareButton.setActionCommand("Share My Sheet!");
        shareButton.setFocusable(false);
        shareButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shareButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        shareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(shareButton);

        jScrollPane1.setViewportView(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("" + shareButton.isSelected());
        if (shareButton.isSelected()) {
            this.timer = new Timer();
            this.alarmClock = new AlarmClock(this.name, this.socket);
            this.timer.scheduleAtFixedRate(this.alarmClock, 0, Main.TIME);
            shareButton.setText("Stop sharing it!");
        } else {
            this.timer.cancel();
            shareButton.setText("Share My Sheet!");
        }
    }//GEN-LAST:event_shareButtonActionPerformed

    public void receiveMessage(Message message) {
        // Verificar se a aba existe, se existir, atualizo.
        ByteArrayInputStream bais = new ByteArrayInputStream(message.getImageByte());
        BufferedImage image;
        Component tab = null;
        try {
            for (int i = 0; i < jTabbedPane1.getTabCount(); i++) {
                String name = jTabbedPane1.getTitleAt(i);
                if (name.equals(message.getName())) {
                    image = ImageIO.read(bais);
                    JLabel myShoot = new JLabel(new ImageIcon(image));
                    jTabbedPane1.setComponentAt(i, myShoot);
                    return;
                }
            }

            image = ImageIO.read(bais);
            JLabel myShoot = new JLabel(new ImageIcon(image));
            jTabbedPane1.addTab(message.getName(), myShoot);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton shareButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the port
     */
    public int getPort() {
        return port;
    }

    /**
     * @param port the port to set
     */
    public void setPort(int port) {
        this.port = port;
    }

}
